apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-busybox
  labels:
    app: busybox
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: busybox
        image: tanmay8898/busybox:1
        ports:
        - containerPort: 80
